framework:
    rate_limiter:
        contact_limiter:
            policy: 'fixed_window'
            limit: 5
            interval: '1 hour'
            lock_factory: 'lock.factory'
            storage_service: null